### ISSUE TITLE
I can not copy files to the board

### ISSUE THREAD

**Issue by fandres** [adafruit/ampy#21]
I can not copy files or create directories on the board (if I execute them and get them)
Error: ampy --port /dev/ttyUSB0 mkdir foo
Traceback (most recent call last):
  File "/usr/local/bin/ampy", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ampy/cli.py", line 122, in mkdir
    board_files.mkdir(directory)
  File "/usr/local/lib/python3.4/dist-packages/ampy/files.py", line 122, in mkdir
    raise ex
  File "/usr/local/lib/python3.4/dist-packages/ampy/files.py", line 116, in mkdir
    out = self._pyboard.exec_(textwrap.dedent(command))
  File "/usr/local/lib/python3.4/dist-packages/ampy/pyboard.py", line 257, in exec_
    raise PyboardError('exception', ret, ret_err)
ampy.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 3, in <module>\r\n  File "flashbdev.py", line 20, in writeblocks\r\nOSError: [Errno 5] EIO\r\n')

**Comment by fandres** [comment]
I use MicroPython v1.8.7-348-gfe866d9 on 2017-03-06; ESP module with ESP8266 (EAP-12E)

**Comment by fandres** [comment]
Hello, I have solved the problem by updating MicroPython v1.8.7-672-g11a9620 on 2017-04-28. I'm not sure if it was the file system or bad firmware, maybe a bad parameter when uploading the firmware.
