### ISSUE TITLE
not working on win10 with esp32s

### ISSUE THREAD

**Issue by Easydo1** [adafruit/ampy#52]
Hi,

I've just installed ampy and it is not working on my setup. I run win10, try to communicate with and old version ESP32. Python version is 3.7. Here is the readout from cmd.exe.

C:\Users\Ivo\AppData\Local\Programs\Python\Python37\Scripts>ampy --port COM3 ls
b'\x1b[0;32mI (396) cpu_start: Pro cpu up.\x1b[0m\r\n\x1b[0;32mI (396) cpu_start: Single core mode\x1b[0m\r\n\x1b[0;32mI (396) heap_init: Initializing. RAM available for dynamic allocation:\x1b[0m\r\n\x1b[0;32mI (399) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM\x1b[0m\r\n\x1b[0;32mI (405) heap_init: At 3FFC5858 len 0001A7A8 (105 KiB): DRAM\x1b[0m\r\n\x1b[0;32mI (412) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM\x1b[0m\r\n\x1b[0;32mI (418) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM\x1b[0m\r\n\x1b[0;32mI (424) heap_init: At 40091B28 len 0000E4D8 (57 KiB): IRAM\x1b[0m\r\n\x1b[0;32mI (431) cpu_start: Pro cpu start user code\x1b[0m\r\n\x1b[0;32mI (225) cpu_start: Starting scheduler on PRO CPU.\x1b[0m\r\nOSError: [Errno 2] ENOENT\r\nMicroPython v1.9.4-241-g14ab81e8 on 2018-07-04; ESP32 module with ESP32\r\nType "help()" for more information.\r\n>>> '
Traceback (most recent call last):
  File "C:\Users\Ivo\AppData\Local\Programs\Python\Python37\Scripts\ampy-script.py", line 11, in <module>
    load_entry_point('adafruit-ampy==1.0.3', 'console_scripts', 'ampy')()
  File "c:\users\ivo\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ivo\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\ivo\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ivo\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ivo\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ivo\appdata\local\programs\python\python37\lib\site-packages\ampy\cli.py", line 147, in ls
    for f in board_files.ls(directory):
  File "c:\users\ivo\appdata\local\programs\python\python37\lib\site-packages\ampy\files.py", line 94, in ls
    self._pyboard.enter_raw_repl()
  File "c:\users\ivo\appdata\local\programs\python\python37\lib\site-packages\ampy\pyboard.py", line 192, in enter_raw_repl
    raise PyboardError('could not enter raw repl')
ampy.pyboard.PyboardError: could not enter raw repl

C:\Users\Ivo\AppData\Local\Programs\Python\Python37\Scripts>

**Comment by cs0ckn** [comment]
I have found that using the delay parameter for one second (ie. -d 1) helps. Also, I had to revert back to earlier Silicon Labs USB drivers from the current ones (that are described as "CP210x_Universal_Windows_Driver").  The drivers I'm using show up as version "6.7.4.261" and dated "19/09/2016". I'm also on Python 3.6.5 so haven't tried with 3.7 yet.

**Comment by ladyada** [comment]
Hiya! We are discontinuing support for ampy, and will no longer be maintaining it. We are leaving this repository available for continued use. If you would like to take over supporting it, please contact us on the Adafruit Discord server and we can transfer the repository to you.
If you wish to continue developing it on your own, please fork the repository.
